finished main code
gen-maksim/otus-hw pull request #7
Opened 2024-07-19 14:29 UTC by gen-maksim

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [x] Пайплайн зелёный - 4 балла
- [x] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-07-24 10:05 UTC, agneum requested changes
Спасибо за вариант решения. 
Хорошая работа, однако есть несколько существенных замечаний

Рекомендую обратить внимание на секцию [Подсказки](https://github.com/OtusGolang/home_work/tree/master/hw07_file_copying#%D0%BF%D0%BE%D0%B4%D1%81%D0%BA%D0%B0%D0%B7%D0%BA%D0%B8) и использовать для копирования `ProxyReader` из пакета https://github.com/cheggaaa/pb?tab=readme-ov-file#progress-bar-for-io-operations и `io.CopyN`

2024-07-24 10:05 UTC, agneum commented on hw07_file_copying/copy.go
> +		time.Sleep(1000 * time.Millisecond)
Зачем ждать секунду с прогресс-баром?

2024-07-24 10:05 UTC, agneum commented on hw07_file_copying/copy.go
> +		bar = pb.Full.Start(contentSize * 2)
Почему x2? То есть до 50% - только чтение, а после 50% - запись?
Вероятно, у них и скорость будет разная. Предлагаю не хранить весь контент в памяти и отслеживать прогресс по записанным на диск данным

2024-07-24 10:05 UTC, agneum commented on hw07_file_copying/copy.go
> +	content := make([]byte, contentSize)
А если файл такого размера, что не поместится в оперативную память?

2024-07-24 10:05 UTC, agneum commented on hw07_file_copying/copy.go
> +	reader := crlf.NewReader(rFile)
На мой взгляд, использование сторонних пакетов из-за проблем на машине разработки, не правильный путь решения.
Почему в принципе содержимое файла влияет на процесс копирования?

2024-07-24 10:05 UTC, agneum commented on hw07_file_copying/copy_test.go
> +		defer os.Remove("testdata/output.txt")
При работе в тестах с файлами, особенно при удалении, рекомендую использовать https://pkg.go.dev/os#CreateTemp или https://pkg.go.dev/os#MkdirTemp

2024-07-30 11:05 UTC, gen-maksim commented on hw07_file_copying/copy.go
> +		time.Sleep(1000 * time.Millisecond)
Это было для большей визуализции. иначе отрабатывало всё мгновенно)
Убрал.

2024-07-30 11:06 UTC, gen-maksim commented on hw07_file_copying/copy.go
> +		bar = pb.Full.Start(contentSize * 2)
Это для того, чтобы указать общий размер прогресса. 100% - это объём считывания + объём записи. а тут оба объёма одинаковые, так что объём считывания*2.
Тут не контент сам, а его размер.

2024-07-30 11:07 UTC, gen-maksim commented on hw07_file_copying/copy.go
> +	content := make([]byte, contentSize)
Изменил отдельное чтение/запись на copyN

2024-07-30 11:07 UTC, gen-maksim commented on hw07_file_copying/copy_test.go
> +		defer os.Remove("testdata/output.txt")
использовал createTemp

2024-07-30 11:12 UTC, gen-maksim commented on hw07_file_copying/copy.go
> +	reader := crlf.NewReader(rFile)
Содержимое файла влияло потому, что input.txt и все тестовые output создались с символом новой строки от винды (/r/n). А созданы эти файлы были с учётом новой строки линукса или мака /n или /r.
Из за этого баш тесты не проходили. Эти два байта переноса съедали символы по сравнению с эталонными /n.
В итоге, я решил просто конвертировать все /r/n в просто /n, благо это делается средствами ide.

2024-07-31 09:11 UTC, agneum approved these changes
Спасибо за правки. Хорошая работа
Итого: 9 баллов из 10. Принято

2024-07-31 09:11 UTC, agneum commented on hw07_file_copying/copy.go
> +	nw := io.Writer(wFile)
`os.File` уже имплементирует интерфейсы `Reader` и `Writer`

2024-07-31 09:11 UTC, agneum commented on hw07_file_copying/copy.go
> +		nw = bar.NewProxyWriter(nw)
`ProxyReader` достаточно для отображения прогресса, т.к. все прочитанные данные будут записаны, на 2 можно не умножать

2024-07-31 09:11 UTC, agneum commented on .golangci.yml
> +          - github.com/andybalholm/crlf
Похоже, эта зависимость больше не нужна

2024-08-05 08:57 UTC, merged