Hw09 struct validator
gen-maksim/otus-hw pull request #9
Opened 2024-09-03 10:51 UTC by gen-maksim

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-09-04 09:18 UTC, agneum requested changes
Спасибо за вариант решения.
Хорошая работа, однако есть существенные замечания. 
Рекомендовал бы перечитать описание задания и обратить внимание на секцию частых ошибок.

2024-09-04 09:18 UTC, agneum commented on hw09_struct_validator/go.mod
> +module github.com/gen-maksim/otus-hw/hw09structvalidator
По-хорошему путь в модуле должен совпадать с директорией, в которой модуль располагается

2024-09-04 09:18 UTC, agneum commented on hw09_struct_validator/validate_int.go
> +		oneVal := strings.Split(oneRawVal, ":")
Определение правила и значения лучше выполнить уровнем выше, иначе она будет повторяться в каждом валидаторе

2024-09-04 09:18 UTC, agneum commented on hw09_struct_validator/validate_int.go
> +			err = validateIn(strconv.FormatInt(s.Int(), 10), oneVal[1])
Размер слайса `oneVal` желательно проверить - там может не оказаться двух элементов. В этом случае будет паника

2024-09-04 09:18 UTC, agneum commented on hw09_struct_validator/validate_int.go
> +			minV, _ := strconv.Atoi(oneVal[1])
Ошибки важно обрабатывать

2024-09-04 09:18 UTC, agneum commented on hw09_struct_validator/validate_strings.go
> +			err = validateRegex(s.String(), oneVal[1])
Те же комментарии, что при валидации численных полей

2024-09-04 09:18 UTC, agneum commented on hw09_struct_validator/validate_strings.go
> +		return errors.New("length should be less than or equal to " + length)
Важно различать программную ошибку и ошибку валидации

2024-09-04 09:18 UTC, agneum commented on hw09_struct_validator/validator.go
> +	result := "Validation Errors:\n"
Рекомендовал бы использовать `strings.Builder`

2024-09-04 09:18 UTC, agneum commented on hw09_struct_validator/validator.go
> +		if alias, ok := field.Tag.Lookup("validate"); ok {
Обычно принято уменьшать уровень вложенности.
Т.е. если не `ok`, то `continue` - следующая итерация цикла. Вся последующая логика идет без вложенности

2024-09-04 09:18 UTC, agneum commented on hw09_struct_validator/validator.go
> +	rt := reflect.TypeOf(v)
А если `v` - не структура?

2024-09-04 09:18 UTC, agneum commented on hw09_struct_validator/validator_test.go
> +				require.Equal(t, tt.expectedErr, err)
Рекомендую использовать `errors.Is` / `errors.As`

2024-09-04 09:18 UTC, agneum commented on hw09_struct_validator/validator.go
> +	}
>Типы полей, которые обязательно должны поддерживаться:
> - int, []int;
> - string, []string.

Не хватает обработки слайсов

2024-09-09 12:53 UTC, gen-maksim commented on hw09_struct_validator/validator.go
> +	}
Добавил.

2024-09-09 12:53 UTC, gen-maksim commented on hw09_struct_validator/validate_int.go
> +			err = validateIn(strconv.FormatInt(s.Int(), 10), oneVal[1])
Исправил уровнем выше.

2024-09-09 12:54 UTC, gen-maksim commented on hw09_struct_validator/validator.go
> +		if alias, ok := field.Tag.Lookup("validate"); ok {
Сократил

2024-09-09 12:54 UTC, gen-maksim commented on hw09_struct_validator/validator.go
> +	rt := reflect.TypeOf(v)
Проверил)

2024-09-09 12:54 UTC, gen-maksim commented on hw09_struct_validator/validator_test.go
> +				require.Equal(t, tt.expectedErr, err)
Использовал ErrorIs

2024-09-10 08:36 UTC, agneum approved these changes
Спасибо за правки. Хорошая работа.
Итого: 9 баллов из 10. Принято

2024-09-10 08:36 UTC, agneum commented on hw09_struct_validator/validator.go
> +			}
Идеоматичнее проверить, что ошибка не является `ValidationErrors`, и завершить выполнение функции в этом случае. Это позволит записать условие без `else`

2024-09-10 08:36 UTC, agneum commented on hw09_struct_validator/validate_int.go
> +			err = validateIn(strconv.FormatInt(s.Int(), 10), oneVal[1])
Здесь всё-таки нет защиты от паники, `validatorAr` может содержать пустой слайс. Например, при рефакторинге кода или добавлении новых вызовов функции `validateInt`, т.к. в месте вызова нет обязательных требований, чтобы передаваемый слайс содержал минимум 2 элемента.

Чтобы это исправить и не проверять в каждой функции размер слайса, можно вместо `[]string` использовать структуру, которая содержит два поля: ключ валидатора и его значение

2024-09-24 09:24 UTC, merged